-- -*- sql-product: postgres; -*-

-- create or replace function call_together_chat(
--   prompt text,
--   model text default 'deepseek-ai/DeepSeek-V3',
--   temperature real default 0.7,
--   max_tokens integer default 512
-- )
--   returns text
--   language sql
--   stable
-- as $function$
--   select
--   *
--   from
--   http(
--     (
--       'POST',
--       'https://api.together.xyz/v1/chat/completions',
--       array[http_header('Authorization', 'Bearer foo')],
--       'application/json',
--       jsonb_build_object(
-- 	'model', 'deepseek-ai/DeepSeek-V3',
-- 	'messages', jsonb_build_array(
-- 	  'role', 'user',
-- 	  'content', prompt)),
-- 	  'stream', false)::text)
-- $function$;
